run:
    # include test files or not, default is true
    tests: false

linters:
    enable:
        - asciicheck
        - bodyclose
        - cyclop
        - dogsled
        - durationcheck
        - errname
        - errorlint
        - exhaustive
        - exportloopref
        - forbidigo
        - forcetypeassert
        - funlen
        - gci
        - gocognit
        - goconst
        - gocritic
        - gocyclo
        - goerr113
        - goprintffuncname
        - gosec
        - ifshort
        - importas
        - lll
        - makezero
        - misspell
        - nakedret
        - nestif
        - nilerr
        - nlreturn
        - noctx
        - nolintlint
        - paralleltest
        - prealloc
        - predeclared
        - revive
        - rowserrcheck
        - exportloopref
        - sqlclosecheck
        - stylecheck
        - thelper
        - tparallel
        - unconvert
        - unparam
        - wastedassign
        - whitespace
        - wsl
        - tagliatelle