apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: XXXX
    server: https://127.0.0.1:42051
  name: kind-kind
contexts:
- context:
    cluster: kind-kind
    user: kind-kind
  name: kind-kind
current-context: kind-kind
kind: Config
preferences: {}
users:
- name: kind-kind
  user:
    client-certificate-data: XXXX
    client-key-data: XXXX
